
global:
  scrape_interval: 5s
  external_labels:
    monitor: 'my-monitor'

scrape_configs:
  - job_name: 'runner'
    honor_labels: true
    static_configs:
      - targets: ['runner:4557']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
