
global:
  scrape_interval: 5s
  external_labels:
    monitor: 'my-monitor'

scrape_configs:
  - job_name: 'differ'
    honor_labels: true
    static_configs:
      - targets: ['differ:4567']
  - job_name: 'saver'
    honor_labels: true
    static_configs:
      - targets: ['saver:4537']
  - job_name: 'runner'
    honor_labels: true
    static_configs:
      - targets: ['runner:4597']      
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
